version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/seedfi-backend-test
file_exists_behavior: OVERWRITE
hooks:
  # ApplicationStop:
  #   - location: stop-application.sh
  #     timeout: 300
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: ubuntu 
  # AfterInstall:
  #   - location: scripts/after-install.sh
  #     timeout: 300
  ApplicationStart:
    - location: start-application.sh
      timeout: 300
      runas: ubuntu 