const {
  SEEDFI_NODE_ENV,
  SEEDFI_DEV_PORT,
  SEEDFI_DEV_DATABASE_URL,
  SEEDFI_DEV_MESSAGE_FORWARDING,
  SEEDFI_DEV_AFRICASTALKING_SMS_API_KEY,
  SEEDFI_DEV_AFRICASTALKING_SMS_USERNAME,
  SEEDFI_DEV_AFRICASTALKING_SMS_SENDER_ID,
  SEEDFI_DEV_STERLING_APIS_BASE_URL,
  SEEDFI_DEV_ENCODING_AUTHENTICATION_SECRET,
  SEEDFI_DEV_BCRYPT_SALT_ROUND,
  SEEDFI_DEV_SENDGRID_API_KEY,
  SEEDFI_DEV_SENDGRID_FROM,
  SEEDFI_DEV_BACKEND_BASE_URL,
  SEEDFI_DEV_VERIFY_EMAIL_MOBILE_REDIRECT_URL,
  SEEDFI_DEV_ADMIN_WEB_BASE_URL
} = process.env;

export default {
  SEEDFI_NODE_ENV,
  SEEDFI_PORT: SEEDFI_DEV_PORT,
  SEEDFI_DATABASE_URL: SEEDFI_DEV_DATABASE_URL,
  SEEDFI_MESSAGE_FORWARDING: SEEDFI_DEV_MESSAGE_FORWARDING,
  SEEDFI_AFRICASTALKING_SMS_API_KEY: SEEDFI_DEV_AFRICASTALKING_SMS_API_KEY,
  SEEDFI_AFRICASTALKING_SMS_USERNAME: SEEDFI_DEV_AFRICASTALKING_SMS_USERNAME,
  SEEDFI_AFRICASTALKING_SMS_SENDER_ID: SEEDFI_DEV_AFRICASTALKING_SMS_SENDER_ID,
  SEEDFI_STERLING_APIS_BASE_URL: SEEDFI_DEV_STERLING_APIS_BASE_URL,
  SEEDFI_ENCODING_AUTHENTICATION_SECRET: SEEDFI_DEV_ENCODING_AUTHENTICATION_SECRET,
  SEEDFI_BCRYPT_SALT_ROUND: SEEDFI_DEV_BCRYPT_SALT_ROUND,
  SEEDFI_SENDGRID_API_KEY: SEEDFI_DEV_SENDGRID_API_KEY,
  SEEDFI_SENDGRID_FROM: SEEDFI_DEV_SENDGRID_FROM,
  SEEDFI_BACKEND_BASE_URL: SEEDFI_DEV_BACKEND_BASE_URL,
  SEEDFI_VERIFY_EMAIL_MOBILE_REDIRECT_URL: SEEDFI_DEV_VERIFY_EMAIL_MOBILE_REDIRECT_URL,
  SEEDFI_ADMIN_WEB_BASE_URL: SEEDFI_DEV_ADMIN_WEB_BASE_URL
};
