const {
  SEEDFI_NODE_ENV,
  SEEDFI_DEV_PORT,
  SEEDFI_DEV_DATABASE_URL,
  SEEDFI_DEV_MESSAGE_FORWARDING,
  SEEDFI_DEV_AFRICASTALKING_SMS_API_KEY,
  SEEDFI_DEV_AFRICASTALKING_SMS_USERNAME,
  SEEDFI_DEV_AFRICASTALKING_SMS_SENDER_ID,
  SEEDFI_DEV_ENCODING_AUTHENTICATION_SECRET,
  SEEDFI_DEV_BCRYPT_SALT_ROUND
} = process.env;

export default {
  SEEDFI_NODE_ENV,
  SEEDFI_PORT: SEEDFI_DEV_PORT,
  SEEDFI_DATABASE_URL: SEEDFI_DEV_DATABASE_URL,
  SEEDFI_MESSAGE_FORWARDING: SEEDFI_DEV_MESSAGE_FORWARDING,
  SEEDFI_AFRICASTALKING_SMS_API_KEY: SEEDFI_DEV_AFRICASTALKING_SMS_API_KEY,
  SEEDFI_AFRICASTALKING_SMS_USERNAME: SEEDFI_DEV_AFRICASTALKING_SMS_USERNAME,
  SEEDFI_AFRICASTALKING_SMS_SENDER_ID: SEEDFI_DEV_AFRICASTALKING_SMS_SENDER_ID,
  SEEDFI_ENCODING_AUTHENTICATION_SECRET: SEEDFI_DEV_ENCODING_AUTHENTICATION_SECRET,
  SEEDFI_BCRYPT_SALT_ROUND: SEEDFI_DEV_BCRYPT_SALT_ROUND
};
