const {
  SEEDFI_NODE_ENV,
  SEEDFI_DEV_PORT,
  SEEDFI_DEV_DATABASE_URL
} = process.env;

export default {
  SEEDFI_NODE_ENV,
  SEEDFI_PORT: SEEDFI_DEV_PORT,
  SEEDFI_DATABASE_URL: SEEDFI_DEV_DATABASE_URL
};
