const {
  SEEDFI_NODE_ENV,
  SEEDFI_TEST_PORT,
  SEEDFI_TEST_DATABASE_URL
} = process.env;

export default {
  SEEDFI_NODE_ENV,
  SEEDFI_PORT: SEEDFI_TEST_PORT,
  SEEDFI_DATABASE_URL: SEEDFI_TEST_DATABASE_URL
};
