apiVersion: v1
kind: Service
metadata:
  labels:
    app: seedfi-api
  name: seedfi-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:804744606457:certificate/b57d5d4f-568b-433c-acc6-ffe56497c042"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: external
    port: 80
    targetPort: 4500
  - name: "https"
    port: 443
    targetPort: 4500
    protocol: "TCP"
  selector:
    app: seedfi-api
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
