apiVersion: v1
kind: Service
metadata:
  labels:
    app: seedfi-api
  name: seedfi-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:804744606457:certificate/a1f1e8e8-d622-4f95-a364-64f4d8db451a"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 4500
    protocol: "TCP"
  selector:
    app: seedfi-api
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
