name: merge_checker
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'master'
      - 'main'
      - 'snapshot'

jobs:
  job1:
    name: check_admin
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN1: ftomiiwo
      NAME_ADMIN2: eloka2023

    steps:
      - name: st1
        if: ${{ github.actor != env.NAME_ADMIN1 && github.actor != env.NAME_ADMIN2 }}
        run: exit 1
      - name: st2
        if: ${{ github.actor == env.NAME_ADMIN1 || github.actor == env.NAME_ADMIN2 }}
        run: echo "ok"
